Run the code cell below.

In [1]:
%load_ext google.colab.data_table

Import the pandas package using the namespace abbreviation `pd`.

In [2]:
# Enter your solution here
import pandas as pd

Import the numpy package with the namespace abbreviation `np`.

In [15]:
# Enter your solution here
import numpy as np

Import the stats module from scipy.

In [3]:
# Enter your solution here
from scipy import stats

Import the `drive` function from the colab module of the google package.

In [4]:
# Enter your solution here
from google.colab import drive

Sign in to your Google Drive with the `drive` function.

In [5]:
# Enter your solution here
drive.mount('/gdrive')

Mounted at /gdrive

Navigate the the DATA directory.

In [6]:
# Enter your solution here
%cd '/gdrive/My Drive/DATA SCIENCE/DATA'

/gdrive/My Drive/DATA SCIENCE/DATA

Import the `client_data.csv` file and assign it to the computer variable `df`.

In [7]:
# Enter your solution here
df = pd.read_csv('client_data.csv')

Display the last five rows to verify that the inport worked.

In [9]:
# Enter your solution here
df.tail()

    first_name  last_name  age  ...  fin_lit_review   savings invest
995      Nancy    Scadden   41  ...            Once  37238.72      1
996      Reese     Brabon   59  ...            Once  31022.55      3
997      Karyl  Latchford   46  ...          Seldom  23185.61      5
998     Weider     Sirmon   37  ...            Once  29032.95      4
999     Maudie   McLellan   30  ...          Seldom  28544.56      3

[5 rows x 11 columns]

What are the sample space elements of the `home_loan` column.

In [11]:
# Enter your solution here
df.home_loan.unique()

array([False,  True])

What is the ferquency of each of the sample space elements of the `home_loan` variable?

In [12]:
# Enter your solution here
df.home_loan.value_counts()

False    515
True     485
Name: home_loan, dtype: int64

Express the answer above as a percentage.

In [14]:
# Enter your solution here
df.home_loan.value_counts(normalize=True) * 100

False    51.5
True     48.5
Name: home_loan, dtype: float64

Create a contignecy table of observed values of the `children` column and the `home_loan` column.

In [17]:
# Enter your solution here
pd.crosstab(df.children, df.home_loan)

home_loan  False  True
children
0            100     82
1             91    103
2            113    101
3            109    109
4            102     90

Print help for the `crosstab` function.

In [18]:
# Enter your solution here
?pd.crosstab

Add margin titles and values to the contingency function. Hint: Use the `margins` argument.

In [23]:
# Enter your solution here
pd.crosstab(df.children, df.home_loan, margins=True)

home_loan  False  True   All
children
0            100    82   182
1             91   103   194
2            113   101   214
3            109   109   218
4            102    90   192
All          515   485  1000

What is the average savings?

In [10]:
# Enter your solution here
df.savings.mean()

30136.492399999974

Show the average value for the `savings` variable for each of the groups in the `home_loan` variable.

In [13]:
# Enter your solution here
df.groupby('home_loan').savings.mean()

home_loan
False    30304.805398
True     29957.768289
Name: savings, dtype: float64

Display only two decimal values in the calculation above. Hint: Use the numpy `round` function.

In [16]:
# Enter your solution here
np.round(df.groupby('home_loan').savings.mean(), decimals=2)

home_loan
False    30304.81
True     29957.77
Name: savings, dtype: float64

What are the median savings of those $50$ and over with no children?

In [26]:
# Enter your solution here
df.loc[(df.age >= 50) & df.children == 0, 'savings'].median()

30256.385000000002

What is the median savings of those $50$ and over with chidren?

In [28]:
# Enter your solution here
df.loc[(df.age >= 50) & (df.children != 0), 'savings'].median()

30182.115

Calculate the variance in savings for all the sample sapce elements of the `invest` column for those younger than $50$.

In [29]:
# Enter your solution here
df.loc[df.age < 50].groupby('invest')['savings'].var()

invest
1    2.139118e+07
2    2.475856e+07
3    1.925683e+07
4    2.481110e+07
5    3.049854e+07
Name: savings, dtype: float64

Calculate the quartile values of savings for each of the home loan groups.

In [31]:
# Enter your solution here
df.groupby('home_loan').savings.quantile([0.25, 0.5, 0.75])

home_loan
False      0.25    27095.765
           0.50    30596.060
           0.75    33450.625
True       0.25    26749.040
           0.50    29903.170
           0.75    33122.220
Name: savings, dtype: float64